version: 2
jobs:
  build:
    working_directory: /go/src/github.com/isacikgoz/libgit2-api
    docker:
      - image: isacikgoz/golang:1.12.5
    steps: # steps that comprise the `build` job
      - run:
          name: donwload git2go
          command:
            go get -d gopkg.in/libgit2/git2go.v27
      - checkout # check out source code to working dir
      - run:
          name: build libgit2
          command:
            chmod +x scripts/circleci-libgit2.sh && ./scripts/circleci-libgit2.sh
      - run:
          name: run tests
          command:
            go test ./... -coverprofile=coverage.txt -covermode=atomic
      - run:
          name: push on codecov result
          command:
            bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
